version: '3.7'

services:
  minio1:
    image: minio/minio:RELEASE.2020-07-13T18-09-56Z
    volumes:
      - miniodata:/miniodata
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /miniodata
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  miniodata: